/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserNotInFraccRouteImport } from './routes/user-not-in-fracc'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as NotFoundRouteImport } from './routes/not-found'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as TenantIdRouteRouteImport } from './routes/$tenantId/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TenantIdIndexRouteImport } from './routes/$tenantId/index'
import { Route as AdminFraccionamientosRouteImport } from './routes/admin/fraccionamientos'
import { Route as TenantIdPerfilRouteImport } from './routes/$tenantId/perfil'
import { Route as TenantIdPagosRouteImport } from './routes/$tenantId/pagos'
import { Route as TenantIdDocumentosRouteImport } from './routes/$tenantId/documentos'
import { Route as TenantIdCasaRouteImport } from './routes/$tenantId/casa'
import { Route as TenantIdAnunciosRouteImport } from './routes/$tenantId/anuncios'

const UserNotInFraccRoute = UserNotInFraccRouteImport.update({
  id: '/user-not-in-fracc',
  path: '/user-not-in-fracc',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const NotFoundRoute = NotFoundRouteImport.update({
  id: '/not-found',
  path: '/not-found',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const TenantIdRouteRoute = TenantIdRouteRouteImport.update({
  id: '/$tenantId',
  path: '/$tenantId',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TenantIdIndexRoute = TenantIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const AdminFraccionamientosRoute = AdminFraccionamientosRouteImport.update({
  id: '/fraccionamientos',
  path: '/fraccionamientos',
  getParentRoute: () => AdminRouteRoute,
} as any)
const TenantIdPerfilRoute = TenantIdPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdPagosRoute = TenantIdPagosRouteImport.update({
  id: '/pagos',
  path: '/pagos',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdDocumentosRoute = TenantIdDocumentosRouteImport.update({
  id: '/documentos',
  path: '/documentos',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdCasaRoute = TenantIdCasaRouteImport.update({
  id: '/casa',
  path: '/casa',
  getParentRoute: () => TenantIdRouteRoute,
} as any)
const TenantIdAnunciosRoute = TenantIdAnunciosRouteImport.update({
  id: '/anuncios',
  path: '/anuncios',
  getParentRoute: () => TenantIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$tenantId': typeof TenantIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/pagos': typeof TenantIdPagosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/$tenantId/': typeof TenantIdIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/pagos': typeof TenantIdPagosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/$tenantId': typeof TenantIdIndexRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$tenantId': typeof TenantIdRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/not-found': typeof NotFoundRoute
  '/signup': typeof SignupRoute
  '/user-not-in-fracc': typeof UserNotInFraccRoute
  '/$tenantId/anuncios': typeof TenantIdAnunciosRoute
  '/$tenantId/casa': typeof TenantIdCasaRoute
  '/$tenantId/documentos': typeof TenantIdDocumentosRoute
  '/$tenantId/pagos': typeof TenantIdPagosRoute
  '/$tenantId/perfil': typeof TenantIdPerfilRoute
  '/admin/fraccionamientos': typeof AdminFraccionamientosRoute
  '/$tenantId/': typeof TenantIdIndexRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$tenantId'
    | '/admin'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/user-not-in-fracc'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/pagos'
    | '/$tenantId/perfil'
    | '/admin/fraccionamientos'
    | '/$tenantId/'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/user-not-in-fracc'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/pagos'
    | '/$tenantId/perfil'
    | '/admin/fraccionamientos'
    | '/$tenantId'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/$tenantId'
    | '/admin'
    | '/login'
    | '/not-found'
    | '/signup'
    | '/user-not-in-fracc'
    | '/$tenantId/anuncios'
    | '/$tenantId/casa'
    | '/$tenantId/documentos'
    | '/$tenantId/pagos'
    | '/$tenantId/perfil'
    | '/admin/fraccionamientos'
    | '/$tenantId/'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TenantIdRouteRoute: typeof TenantIdRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  NotFoundRoute: typeof NotFoundRoute
  SignupRoute: typeof SignupRoute
  UserNotInFraccRoute: typeof UserNotInFraccRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-not-in-fracc': {
      id: '/user-not-in-fracc'
      path: '/user-not-in-fracc'
      fullPath: '/user-not-in-fracc'
      preLoaderRoute: typeof UserNotInFraccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/not-found': {
      id: '/not-found'
      path: '/not-found'
      fullPath: '/not-found'
      preLoaderRoute: typeof NotFoundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$tenantId': {
      id: '/$tenantId'
      path: '/$tenantId'
      fullPath: '/$tenantId'
      preLoaderRoute: typeof TenantIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tenantId/': {
      id: '/$tenantId/'
      path: '/'
      fullPath: '/$tenantId/'
      preLoaderRoute: typeof TenantIdIndexRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/admin/fraccionamientos': {
      id: '/admin/fraccionamientos'
      path: '/fraccionamientos'
      fullPath: '/admin/fraccionamientos'
      preLoaderRoute: typeof AdminFraccionamientosRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/$tenantId/perfil': {
      id: '/$tenantId/perfil'
      path: '/perfil'
      fullPath: '/$tenantId/perfil'
      preLoaderRoute: typeof TenantIdPerfilRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/pagos': {
      id: '/$tenantId/pagos'
      path: '/pagos'
      fullPath: '/$tenantId/pagos'
      preLoaderRoute: typeof TenantIdPagosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/documentos': {
      id: '/$tenantId/documentos'
      path: '/documentos'
      fullPath: '/$tenantId/documentos'
      preLoaderRoute: typeof TenantIdDocumentosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/casa': {
      id: '/$tenantId/casa'
      path: '/casa'
      fullPath: '/$tenantId/casa'
      preLoaderRoute: typeof TenantIdCasaRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
    '/$tenantId/anuncios': {
      id: '/$tenantId/anuncios'
      path: '/anuncios'
      fullPath: '/$tenantId/anuncios'
      preLoaderRoute: typeof TenantIdAnunciosRouteImport
      parentRoute: typeof TenantIdRouteRoute
    }
  }
}

interface TenantIdRouteRouteChildren {
  TenantIdAnunciosRoute: typeof TenantIdAnunciosRoute
  TenantIdCasaRoute: typeof TenantIdCasaRoute
  TenantIdDocumentosRoute: typeof TenantIdDocumentosRoute
  TenantIdPagosRoute: typeof TenantIdPagosRoute
  TenantIdPerfilRoute: typeof TenantIdPerfilRoute
  TenantIdIndexRoute: typeof TenantIdIndexRoute
}

const TenantIdRouteRouteChildren: TenantIdRouteRouteChildren = {
  TenantIdAnunciosRoute: TenantIdAnunciosRoute,
  TenantIdCasaRoute: TenantIdCasaRoute,
  TenantIdDocumentosRoute: TenantIdDocumentosRoute,
  TenantIdPagosRoute: TenantIdPagosRoute,
  TenantIdPerfilRoute: TenantIdPerfilRoute,
  TenantIdIndexRoute: TenantIdIndexRoute,
}

const TenantIdRouteRouteWithChildren = TenantIdRouteRoute._addFileChildren(
  TenantIdRouteRouteChildren,
)

interface AdminRouteRouteChildren {
  AdminFraccionamientosRoute: typeof AdminFraccionamientosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminFraccionamientosRoute: AdminFraccionamientosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TenantIdRouteRoute: TenantIdRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  NotFoundRoute: NotFoundRoute,
  SignupRoute: SignupRoute,
  UserNotInFraccRoute: UserNotInFraccRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
